spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
