spring:
  application:
    name: netflix-eureka-naming-server
  #zipkin:
  #  base-url: http://localhost:9411/
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
