spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Development/udemy/git-localconfig-repo
server:
  port: 8888

